version: '3.8'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_secure_password
      MYSQL_DATABASE: todo_database
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '3001:3001'
    environment:
      DB_HOST: db
      DB_USERNAME: todo_user
      DB_PASSWORD: todo_pass
      DB_DATABASE: todo_database
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend

volumes:
  db_data:
